Fixing latest Godzyk exception
java.lang.RuntimeException: java.lang.ClassCastException:
java.lang.Integer cannot be cast to java.lang.String
	at org.abc.tools.exports.OneRosterExport_1_1_YOG.createUsers(OneRosterExport_1_1_YOG.java:1779)
	at org.abc.tools.exports.OneRosterExport_1_1_YOG.buildBeans(OneRosterExport_1_1_YOG.java:849)
	at org.abc.tools.exports.OneRosterExport_1_1_YOG.gatherData(OneRosterExport_1_1_YOG.java:1934)
	at com.follett.cust.reports.ExportArbor.run(ExportArbor.java:285)
	at com.follett.fsc.core.k12.tools.ToolJob.run(ToolJob.java:657)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be
cast to java.lang.String
	at org.abc.tools.exports.OneRosterExport_1_1_YOG.createUsers(OneRosterExport_1_1_YOG.java:1662)
	... 5 more