Addressing another clone error from customer
java.lang.RuntimeException: java.lang.IllegalAccessException: Class
com.follett.cust.io.exporter.oneroster.OneRosterBean can not access a
member of class
com.x2dev.reports.portable.OneRosterExport_1_1$CustomizedUser with
modifiers "public"
at com.follett.cust.io.exporter.oneroster.OneRosterBean.clone(OneRosterBean.java:70)
at com.x2dev.reports.portable.OneRosterExport_1_1.gatherData(OneRosterExport_1_1.java:1891)
at com.follett.cust.reports.ExportArbor.run(ExportArbor.java:271)
at com.follett.fsc.core.k12.tools.ToolJob.run(ToolJob.java:619)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalAccessException: Class
com.follett.cust.io.exporter.oneroster.OneRosterBean can not access a
member of class
com.x2dev.reports.portable.OneRosterExport_1_1$CustomizedUser with
modifiers "public"
at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
at java.lang.reflect.Constructor.newInstance(Constructor.java:413)
at com.follett.cust.io.exporter.oneroster.OneRosterBean.clone(OneRosterBean.java:54)
... 4 more