Addressing error while cloning CustomizedUser
Cloning requires an empty constructor

java.lang.RuntimeException: java.lang.NoSuchMethodException:
com.x2dev.reports.portable.OneRosterExport_1_1$CustomizedUser.<init>()
at com.follett.cust.io.exporter.oneroster.OneRosterBean.clone(OneRosterBean.java:70)
at com.x2dev.reports.portable.OneRosterExport_1_1.gatherData(OneRosterExport_1_1.java:1884)
at com.follett.cust.reports.ExportArbor.run(ExportArbor.java:271)
at com.follett.fsc.core.k12.tools.ToolJob.run(ToolJob.java:619)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodException:
com.x2dev.reports.portable.OneRosterExport_1_1$CustomizedUser.<init>()
at java.lang.Class.getConstructor0(Class.java:3082)
at java.lang.Class.getConstructor(Class.java:1825)
at com.follett.cust.io.exporter.oneroster.OneRosterBean.clone(OneRosterBean.java:53)
... 4 more