Attempting to resolve a NPE Scott reported.
The line numbers aren't a perfect fit (I wonder if a comment was deleted
or something?), but this is generally consistent with the isPrimary
object being null.

I'm not sure if "true" is the correct default to assume? I'll ask Scott
for more feedback on that.

java.lang.RuntimeException: java.lang.NullPointerException
                at
org.abc.tools.exports.OneRosterExport_1_1_Coteachers.createEnrollments(OneRosterExport_1_1_Coteachers.java:1067)
                at
org.abc.tools.exports.OneRosterExport_1_1_Coteachers.gatherData(OneRosterExport_1_1_Coteachers.java:1821)
                at
com.follett.cust.reports.ExportArbor.run(ExportArbor.java:271)
                at
com.follett.fsc.core.k12.tools.ToolJob.run(ToolJob.java:658)
                at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
                at
org.abc.tools.exports.OneRosterExport_1_1_Coteachers.createEnrollments(OneRosterExport_1_1_Coteachers.java:1047)
                ... 4 more